### ISSUE TITLE
Zemljevid Evrope

### ISSUE THREAD

**Issue by DomenFlakusBosilj** [DomenFlakusBosilj/APPR-2018-19#2]
Pozdravljeni,
za svoj projekt potrebujem zemljevid držav EU in še nekaj drugih evropskih držav.
Na nobeni od povezav ne najdem zemljevida Evrope v celoti in ne vem, kako bi se lotil risanja tega zemljevida, zato bi prosil, če mi lahko pomagate.
Hvala in lep pozdrav

**Comment by MarvinHerzog** [comment]
Pozdravljen!

Predlagam, da si kar izposodiš rešitev tvojega sošolca tukaj:
https://github.com/1312Bravo/APPR-2018-19/blob/master/vizualizacija/vizualizacija.r



```
# 3. faza: Vizualizacija podatkov
library(rgdal)
library(rgeos)
library(mosaic)
library(maptools)
library(reshape2)
library(ggplot2)
library(munsell)

# Uvozimo zemljevid Sveta
# source("https://raw.githubusercontent.com/jaanos/APPR-2018-19/master/lib/uvozi.zemljevid.r")
source("lib/uvozi.zemljevid.r") #Nastavi pravo datoteko

zemljevid <- uvozi.zemljevid("https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/cultural/ne_50m_admin_0_countries.zip",
                             "ne_50m_admin_0_countries") %>%
  fortify()


# Zemljevid sveta skrčimo na zemljevid Evrope
Evropa <- filter(zemljevid, CONTINENT == "Europe" |NAME == "Turkey")
Evropa <- filter(Evropa, long < 55 & long > -45 & lat > 30 & lat < 85)

ggplot(Evropa, aes(x=long, y=lat, group=group, fill=NAME)) + 
  geom_polygon() + 
  labs(title="Evropa - osnovna slika") +
  theme(legend.position="none")

```

Podatki so sicer iz zemljevida sveta, vendar so s `filter` izbrane samo evropske države in Turčija, hkrati pa je zmanjšano okno v katerem se zemljevid izriše. Zamenjal sem samo ločljivost zemljevida iz 110m na 50m, da so meje nekoliko lepše.

**Comment by DomenFlakusBosilj** [comment]
Hvala!
