### ISSUE TITLE
Poročilo, binder

### ISSUE THREAD

**Issue by MarvinHerzog** [DomenFlakusBosilj/APPR-2018-19#3]
Pozdravljen, pri študentih preverjam kakšno je stanje poročil za četrtkove predstavitve. Vidim, da še nisi spreminjal datoteke *projekt.Rmd*. Če želiš predstaviti svoj projekt v četrtek, svetujem, da pripraviš rmarkdown poročilo. Ko boš imel poročilo  pripravljeno (ali v primeru, da boš imel težave) in se bo to uspešno prevedlo na Binderju [![Shiny](http://mybinder.org/badge.svg)](http://beta.mybinder.org/v2/gh/DomenFlakusBosilj/APPR-2018-19/master?urlpath=shiny/APPR-2018-19/projekt_domen.Rmd), komentiraj na tale issue, da dodamo tvoj projekt na [repozitorij za zagovore](https://github.com/jaanos/APPR-zagovori).

**Comment by DomenFlakusBosilj** [comment]
Pozdravljeni, poročilo v rmarkdownu sem naredil do te mere, da deluje, nameraval pa sem jutri vključiti še nekaj grafov ter urediti zemljevid.
Težavo pa imam pri prevajanju na Binderju, kjer mi javlja error, zato bi prosil če mi lahko pri tem pomagate.
Hvala in lep pozdrav.

**Comment by jaanos** [comment]
Kolikor vidim, tvoje poročilo nastaja v datoteki `projekt_domen.Rmd`, tako da bo potrebno popraviti prvo povezavo za Binder v `README.md`:
```markdown
* [![Shiny](http://mybinder.org/badge.svg)](http://beta.mybinder.org/v2/gh/DomenFlakusBosilj/APPR-2018-19/master?urlpath=shiny/APPR-2018-19/projekt_domen.Rmd) Shiny
```

Trenutno se poročilo sicer ne prevede - problem je tukaj:

https://github.com/DomenFlakusBosilj/APPR-2018-19/blob/f197ea1262b4d9c1d3b251eff37a7993586fc1ea/projekt_domen.Rmd#L70

Ker imaš v mapi `vizualizacija` program `vizualizacija_domen.R` (velika črka v končnici!), bo tako treba popraviti tudi v poročilu.

**Comment by DomenFlakusBosilj** [comment]
Hvala za pomoč!
Sedaj mi poročilo deluje na Binderju tako da mislim da je pripravljeno za jutrišnje predstavitve.

**Comment by MarvinHerzog** [comment]
Velja, bomo dodali na skupni repozitorij. Če boš še kaj spreminjal projekt, odpri issue [tukaj](https://github.com/jaanos/APPR-zagovori/tree/master/2018-19/2019-01-17-predstavitve), da posodobimo povezavo. Šifra tvojega zadnjega commita [tukaj](https://github.com/DomenFlakusBosilj/APPR-2018-19/commits/master) se mora ujemati s šifro ob tvojem projektu [tukaj](https://github.com/jaanos/APPR-zagovori/tree/master/2018-19/2019-01-17-predstavitve).

Mimogrede, morda ti bi bil bolj všeč prikaz grafov, če narediš to dvoje:
* V *vizualizacija_domen.R* poskusi spremeniti vse `facet_grid( . ~ Drzava)` v `facet_grid(  Drzava~.)`
* V *projekt_domen.Rmd* v bloka `{r line}` ter `{r graf_smrti}` dodaj parameter `fig.height=20`

V tem primeru se grafa, ki sta trenutno nekoliko stisnjena, prikažeta tako:

![image](https://user-images.githubusercontent.com/4990893/51275942-a5163280-19d3-11e9-9440-f9af35882ec3.png)
