### ISSUE TITLE
Zaključek

### ISSUE THREAD

**Issue by DomenFlakusBosilj** [DomenFlakusBosilj/APPR-2018-19#4]
Pozdravljeni,
s svojim projektom sem že skoraj zaključil, zanima me samo še ali naj vključim tabelo, ki je čisto na koncu poročila(cluster), ki prikazuje razporeditev držav v skupine glede na bdppc in varnost. Če je bolje da jo pustim v poročilu, jo bom še uredil, v nasprotnem primeru pa jo odstranim in lahko pustim le komentar o ugotovitvi.
Ostalo pa mislim da je dokončano v skladu z navodili.
Hvala za pomoč in lep pozdrav,
Domen Flakus Bosilj

**Comment by jaanos** [comment]
Namesto razpredelnice razdelitev raje prikaži na zemljevidu. Raje kot da delaš dve razdelitvi po eni spremenljivki, naredi eno spremenljivko po vseh spremenljivkah, ki jih imaš (lahko vzameš podatke za vsako leto kot eno spremenljivko - pri pretvorbi iz oblike *tidy data* si lahko pomagaš s funkcijo `dcast` iz knjižnice `reshape2`).

Na prvem in tretjem grafu prikazuješ podatke za vsako državo - glede na to, da imaš za vsako državo več kategorij, je smiselno imeti en graf na državo, a bo bolje, če ne prikažeš čisto vseh podatkov, pač pa izbereš le najzanimivejše države (kaj se dogaja v drugih, lahko na kratko opišeš v besedilu - ali pa ta prikaz narediš v Shiny aplikaciji). Poskrbi tudi za šumnike v naslovih grafov in oznakah osi ter za ustrezne naslove legend.

**Comment by DomenFlakusBosilj** [comment]
Sem popravil razdelitve tako da sem uporabil vsa leta, ki sem jih imel na voljo. Prav tako sem razdelitve prikazal na zemljevidih.
Na prvem in tretjem grafu sem odstranil države, da ni prikazanih preveč podatkov.
Popravil sem vse oznake osi, naslove grafov ter legend.
Težave sem imel le pri uporabi črke Č (vsi ostali šumniki mi delujejo), teh težav pa mi ni uspelo odpraviti, zato prosim za pomoč.
Hvala in lep pozdrav,
Domen Flakus Bosilj

**Comment by jaanos** [comment]
Pri meni šumniki delujejo. Lahko morda poskusiš v glavo poročila dodati vrstico `runtime: shiny`, če bo kaj drugače. Bi prosil še @MarvinHerzog, da preveriš, če šumniki delujejo pri tebi.

Kar se tiče razdelitev, sem mislil, da uporabiš tako podatke iz `smrti_pmio_avto` kot iz `bdppc_a`, da dobiš eno samo razdelitev (zanima te morda, kakšna je povezava med BDP in številom smrti - razvrščanje v skupine ti potem da neko sliko, katere države so bolj podobne med sabo v teh dveh pogledih). Ko prikazuješ skupine na zemljevidu, njihove številke nimajo nobene urejenosti, tako da iz njih naredi `factor` (podobno kot pri letih na stolpčnem grafu), da bo vsaka dobila svojo barvo in ne le svojega odtenka - tako bo tudi lažje ločiti med skupinami.

Opozoril bi še na sledeče:

https://github.com/DomenFlakusBosilj/APPR-2018-19/blob/d9b28fd909536ac91dcd162301a65e47beeb426f/projekt_domen.Rmd#L135

V imenih blokov kode v poročilu naj ne bo presledkov (pa tudi ne šumnikov in drugih posebnih znakov), sicer se ustrezni grafi ne bodo prikazali, ko projekt poženeš v Binderju. Pri zadnjih treh grafih torej popravi to ime, da ne bo imelo presledka (lahko ga nadomestiš npr. s podčrtajem ali piko).

Še to: ali obstaja kak poseben razlog, da na zemljevidu ne prikazuješ Črne gore in Ukrajine? Svetujem, da ju vključiš na zemljevid (tudi, če zanju nimaš podatkov), da ta ne bo imel lukenj.

**Comment by MarvinHerzog** [comment]
Pozdravljena, na službenem računalniku mi vse šumnike prevede pravilno. Bom zvečer preveril še na domačem računalniku in poskusil popraviti, če mi jih tam ne bo prevedlo.

**Comment by DomenFlakusBosilj** [comment]
Pozdravljeni, popravil sem imena blokov, naredil novo razdelitev, ki je prikazana na Zemljevid 2, prejšnji razdelitvi pa sem pustil v poročilu, lahko pa ju tudi odstranim. Popravil sem tudi vse zemljevide(factor) ter dodal Črno goro in Ukrajino.
Hvala za pomoč in lep pozdrav,
Domen Flakus Bosilj

**Comment by MarvinHerzog** [comment]
Ok, našel sem računalnik kjer mi šumniki ne delajo pravilno. Poskusiš lahko na dva načina:
Prvi je, da spremeniš *locale* za *R*. V enega od začetnih rmarkdown blokov dodaj to vrstico:

```
Sys.setlocale("LC_ALL","Slovenian")
```
Če ti to ne bo delovalo, lahko poskusiš zamenjati vse *č*-je z `\U0010D` (oz `\U0010C` za veliki *Č*), npr. tako:
`Koli\U0010Dina toplogrednih plinov v ozra\U0010Dju`

**Comment by DomenFlakusBosilj** [comment]
Je delovala prva rešitev. Najlepša hvala!

**Comment by jaanos** [comment]
Sem dodal povezavo na repozitorij za zagovore, tako da se lahko z @alenFMF domeniš za termin zagovora, če se še nisi. Če boš še kaj spreminjal, prosim javi, da posodobim povezavo.

**Comment by DomenFlakusBosilj** [comment]
Pozdravljeni,
naredil sem nekaj popravkov, da nekateri grafi izgledajo lepše, zato prosim, da dodate novo povezavo na repozitorij za zagovore.
Lep pozdrav,
Domen Flakus Bosilj

**Comment by jaanos** [comment]
Sem posodobil povezavo.
